<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <style>
        body {
            font-family: DejaVu Sans, sans-serif;
            color: #172033;
            font-size: 13px;
            line-height: 1.45;
        }

        .page {
            padding: 28px 32px;
        }

        h1 {
            font-size: 22px;
            margin: 0 0 16px;
        }

        .box {
            border: 1px solid #d7dde7;
            padding: 16px;
        }

        .label {
            color: #5f6b7a;
            width: 120px;
            display: inline-block;
        }
    </style>
</head>
<body>
    <div class="page">
        <h1>Quote Mail Diagnostic PDF</h1>
        <div class="box">
            <p>This PDF was generated by KIJO to test the quotation email attachment pipeline.</p>
            <p><span class="label">Generated</span>{{ $generatedAt }}</p>
            <p><span class="label">Requested by</span>{{ $generatedBy }}</p>
        </div>
    </div>
</body>
</html>
