<?php

namespace App\Support;

class PdfLegalTerms
{
    private const TERMS = [
        'training_quote' => [
            'en' => [
                'This quotation is valid for thirty (30) days from the issue date.',
                'Confirmation of training is subject to the receipt of a valid Purchase Order, signed quotation, or approved HRD Corp grant prior to the training date.',
                'The training date will only be confirmed and locked upon receipt of any of the above confirmations.',
                'For HRD Corp claimable training, a minimum of five (5) confirmed participants is required for in-house sessions.',
                'If the approved HRD Corp grant amount is less than the original quotation value, the Client shall be responsible for paying the difference directly to AMIOSH Resources Sdn. Bhd. Certificates of attendance will only be issued upon full settlement of the quotation value.',
                'For non-HRD Corp claimable training, full payment is required at least three (3) working days prior to the training date.',
                'Cancellation or postponement must be notified in writing at least seven (7) working days prior to the scheduled training date. Failure to do so may result in forfeiture of payment or rescheduling charges.',
                'AMIOSH Resources Sdn. Bhd. reserves the right to assign or reassign trainers without prior notice to ensure the program proceeds as scheduled.',
                'All printed materials (e.g., lecture notes, certificates, competency cards) will be prepared strictly based on the number of participants stated in this quotation.',
                'No soft copies of training materials will be provided. Only hard copies will be distributed to participants.',
                'Certificates and related documentation will be issued only upon receipt of full payment (for non-HRD Corp Clients) and the returned copy of the HRD Corp JD-14 form (for HRD Corp claimable training).',
                'All prices quoted are exclusive of SST (8%) where applicable.',
                'This engagement shall be governed by and construed in accordance with the laws of Malaysia.',
            ],
            'ms-MY' => [
                'Sebut harga ini sah selama tiga puluh (30) hari dari tarikh dikeluarkan.',
                'Pengesahan latihan adalah tertakluk kepada penerimaan Pesanan Belian yang sah, sebut harga yang telah ditandatangani, atau geran HRD Corp yang telah diluluskan sebelum tarikh latihan.',
                'Tarikh latihan hanya akan disahkan dan dikunci selepas mana-mana pengesahan di atas diterima.',
                'Bagi latihan yang boleh dituntut melalui HRD Corp, sekurang-kurangnya lima (5) peserta yang disahkan diperlukan untuk sesi dalaman.',
                'Sekiranya jumlah geran HRD Corp yang diluluskan adalah kurang daripada nilai sebut harga asal, Pelanggan bertanggungjawab untuk membayar perbezaan tersebut terus kepada AMIOSH Resources Sdn. Bhd. Sijil kehadiran hanya akan dikeluarkan selepas nilai sebut harga dijelaskan sepenuhnya.',
                'Bagi latihan yang tidak boleh dituntut melalui HRD Corp, bayaran penuh hendaklah dibuat sekurang-kurangnya tiga (3) hari bekerja sebelum tarikh latihan.',
                'Pembatalan atau penangguhan hendaklah dimaklumkan secara bertulis sekurang-kurangnya tujuh (7) hari bekerja sebelum tarikh latihan yang dijadualkan. Kegagalan berbuat demikian boleh menyebabkan bayaran dilucut hak atau caj penjadualan semula dikenakan.',
                'AMIOSH Resources Sdn. Bhd. berhak melantik atau menukar jurulatih tanpa notis awal bagi memastikan program berjalan seperti yang dijadualkan.',
                'Semua bahan bercetak (contohnya nota kuliah, sijil dan kad kompetensi) akan disediakan dengan ketat berdasarkan bilangan peserta yang dinyatakan dalam sebut harga ini.',
                'Salinan lembut bahan latihan tidak akan disediakan. Hanya salinan bercetak akan diedarkan kepada peserta.',
                'Sijil dan dokumen berkaitan hanya akan dikeluarkan selepas bayaran penuh diterima (bagi Pelanggan bukan HRD Corp) dan salinan borang HRD Corp JD-14 yang telah dikembalikan diterima (bagi latihan yang boleh dituntut melalui HRD Corp).',
                'Semua harga yang dinyatakan adalah tidak termasuk SST (8%) jika berkaitan.',
                'Urusan ini hendaklah ditadbir dan ditafsirkan mengikut undang-undang Malaysia.',
            ],
        ],
        'ih_general' => [
            'en' => [
                'This quotation is valid for 30 days from the date of issue unless otherwise agreed in writing.',
                'Payment should be made within 30 days of final report delivery.',
                'Cancellation or rescheduling of the service must be notified in writing at least seven (7) working days prior to the scheduled assessment or sampling date. In the event of cancellation, all mobilisation and demobilisation costs incurred will be borne by the Client.',
                'Cancellation or rescheduling must be notified in writing at least three (3) working days prior to the scheduled sampling date. Cancellation within three (3) working days may incur a cancellation fee to cover administrative and preparatory costs.',
                'All data, reports, and printed materials remain the property of AMIOSH Resources Sdn. Bhd. until full payment is received. No part of the report may be reproduced or distributed without prior written consent.',
                'Quotations are based on information provided at the time of issuance. Any variations to scope, site conditions, or Client requirements may result in adjustments to pricing and project timelines.',
                'AMIOSH Resources Sdn. Bhd. reserves the right to subcontract specialist services to qualified third-party professionals where necessary to fulfil project objectives while ensuring compliance with relevant standards.',
                'All professional services will be conducted in accordance with applicable Malaysian laws, Department of Occupational Safety and Health (DOSH) guidelines, and recognised industrial hygiene best practices.',
                'This agreement shall be governed by and construed in accordance with the laws of Malaysia. Any disputes arising shall be subject to the exclusive jurisdiction of Malaysian courts.',
            ],
            'ms-MY' => [
                'Sebut harga ini sah selama 30 hari dari tarikh dikeluarkan melainkan dipersetujui sebaliknya secara bertulis.',
                'Bayaran hendaklah dibuat dalam tempoh 30 hari selepas laporan akhir diserahkan.',
                'Pembatalan atau penjadualan semula perkhidmatan hendaklah dimaklumkan secara bertulis sekurang-kurangnya tujuh (7) hari bekerja sebelum tarikh penilaian atau pensampelan yang dijadualkan. Sekiranya berlaku pembatalan, semua kos mobilisasi dan demobilisasi yang telah ditanggung akan ditanggung oleh Pelanggan.',
                'Pembatalan atau penjadualan semula hendaklah dimaklumkan secara bertulis sekurang-kurangnya tiga (3) hari bekerja sebelum tarikh pensampelan yang dijadualkan. Pembatalan dalam tempoh tiga (3) hari bekerja boleh dikenakan caj pembatalan bagi menampung kos pentadbiran dan persediaan.',
                'Semua data, laporan dan bahan bercetak kekal menjadi hak milik AMIOSH Resources Sdn. Bhd. sehingga bayaran penuh diterima. Tiada bahagian laporan boleh diterbitkan semula atau diedarkan tanpa persetujuan bertulis terlebih dahulu.',
                'Sebut harga adalah berdasarkan maklumat yang diberikan pada masa dikeluarkan. Sebarang perubahan skop, keadaan tapak atau keperluan Pelanggan boleh menyebabkan pelarasan harga dan garis masa projek.',
                'AMIOSH Resources Sdn. Bhd. berhak mensubkontrakkan perkhidmatan pakar kepada profesional pihak ketiga yang berkelayakan jika perlu bagi memenuhi objektif projek sambil memastikan pematuhan kepada standard berkaitan.',
                'Semua perkhidmatan profesional akan dijalankan mengikut undang-undang Malaysia yang terpakai, garis panduan Jabatan Keselamatan dan Kesihatan Pekerjaan (DOSH), dan amalan terbaik higien industri yang diiktiraf.',
                'Perjanjian ini hendaklah ditadbir dan ditafsirkan mengikut undang-undang Malaysia. Sebarang pertikaian yang timbul adalah tertakluk kepada bidang kuasa eksklusif mahkamah Malaysia.',
            ],
        ],
        'ih_technical' => [
            'en' => [
                'Any variation or extension to the agreed scope of work must be supported by an official Variation Order or a separate Purchase Order or Letter of Award, and may be subject to revised pricing and deliverables.',
                'Any additional sampling requirements, increase in the number of systems assessed, or other scope expansions shall incur additional costs, which will be reflected in the final invoice.',
                'The Client must ensure site access, safety inductions, and necessary work permits are arranged and approved at least one (1) working day before sampling activities commence.',
                'Assessment or sampling activities are subject to weather and operational conditions. AMIOSH Resources Sdn. Bhd. will notify the Client promptly and reschedule as required to ensure sampling integrity and validity.',
                'The Client must provide accurate and complete site drawings, process flow information, chemical inventories, and any relevant safety data sheets prior to commencement of work.',
                'The Client shall ensure that AMIOSH Resources Sdn. Bhd. personnel are briefed on all site-specific hazards, emergency procedures, and required personal protective equipment prior to work commencement.',
                'The Client will be informed promptly of any unforeseen technical issues, delays, or additional safety requirements identified during site assessment.',
                'AMIOSH Resources Sdn. Bhd. reserves the right to include in the final invoice any reasonable additional costs incurred due to site access restrictions, standby time, or variations to agreed scope not apparent during the quotation stage.',
                'All sampling and analysis will be conducted in accordance with recognised Malaysian Standards (MS), DOSH Guidelines, and international standards where applicable to ensure data reliability and compliance.',
                'AMIOSH Resources Sdn. Bhd. shall not be held liable for any consequential or indirect losses arising from the use or interpretation of assessment results beyond the scope of the agreed services.',
            ],
            'ms-MY' => [
                'Sebarang perubahan atau lanjutan kepada skop kerja yang dipersetujui hendaklah disokong oleh Variation Order rasmi atau Pesanan Belian atau Surat Setuju Terima yang berasingan, dan boleh tertakluk kepada semakan harga serta serahan kerja.',
                'Sebarang keperluan pensampelan tambahan, peningkatan bilangan sistem yang dinilai, atau peluasan skop lain akan dikenakan kos tambahan yang akan dinyatakan dalam invois akhir.',
                'Pelanggan hendaklah memastikan akses tapak, taklimat keselamatan dan permit kerja yang diperlukan diuruskan dan diluluskan sekurang-kurangnya satu (1) hari bekerja sebelum aktiviti pensampelan bermula.',
                'Aktiviti penilaian atau pensampelan adalah tertakluk kepada keadaan cuaca dan operasi. AMIOSH Resources Sdn. Bhd. akan memaklumkan Pelanggan dengan segera dan menjadualkan semula jika perlu bagi memastikan integriti dan kesahan pensampelan.',
                'Pelanggan hendaklah menyediakan lukisan tapak, maklumat aliran proses, inventori bahan kimia dan helaian data keselamatan yang berkaitan dengan tepat dan lengkap sebelum kerja bermula.',
                'Pelanggan hendaklah memastikan kakitangan AMIOSH Resources Sdn. Bhd. diberi taklimat mengenai semua bahaya khusus tapak, prosedur kecemasan dan peralatan perlindungan diri yang diperlukan sebelum kerja bermula.',
                'Pelanggan akan dimaklumkan dengan segera mengenai sebarang isu teknikal, kelewatan atau keperluan keselamatan tambahan yang tidak dijangka semasa penilaian tapak.',
                'AMIOSH Resources Sdn. Bhd. berhak memasukkan dalam invois akhir sebarang kos tambahan yang munasabah akibat sekatan akses tapak, masa menunggu atau perubahan skop yang dipersetujui tetapi tidak jelas semasa peringkat sebut harga.',
                'Semua pensampelan dan analisis akan dijalankan mengikut Standard Malaysia (MS), Garis Panduan DOSH dan standard antarabangsa yang berkaitan bagi memastikan kebolehpercayaan data dan pematuhan.',
                'AMIOSH Resources Sdn. Bhd. tidak akan bertanggungjawab terhadap sebarang kerugian berbangkit atau tidak langsung yang timbul daripada penggunaan atau tafsiran keputusan penilaian di luar skop perkhidmatan yang dipersetujui.',
            ],
        ],
        'manpower_general' => [
            'en' => [
                'This quotation is valid for thirty (30) days from the date of issuance.',
                'All invoices must be settled within thirty (30) days from the invoice date. Invoices will be submitted on a monthly basis unless otherwise agreed.',
                'All prices stated exclude SST and any other applicable taxes.',
                'Service confirmation must be supported by an official Purchase Order or Letter of Award issued by the Client.',
                'Prices exclude medical check-ups, health screenings, or any additional costs imposed by the Client on supplied personnel, unless disclosed prior to the issuance of this quotation. Any such costs billed to AMIOSH Resources Sdn. Bhd. will be fully claimed from the Client.',
                'Prices exclude travel and accommodation costs for supplied personnel outside of the specified site location unless specifically stated. If travel is required, all related expenses billed to AMIOSH Resources Sdn. Bhd. will be claimed from the Client accordingly.',
                'Prices exclude the cost of trainings or certifications required by the Client (e.g., Authorised Entrant and Standby Person (AESP), Authorised Gas Tester (AGT), etc.). These will be charged separately and claimed from the Client.',
                'Prices exclude liabilities arising from incidents caused by the conduct of supplied personnel in connection with the Client\'s team that result in damage to persons, property, environment, or reputation. AMIOSH Resources Sdn. Bhd. will cooperate fully in any subsequent investigation.',
                'The Client is fully responsible for any injury, harm, or damage incurred by supplied personnel while performing duties within the Client\'s premises or during any work-related travel arranged by the Client.',
                'Service termination must be communicated in writing with a notice period of no less than one (1) month from the intended last service date.',
                'All cheque payments shall be made payable to AMIOSH Resources Sdn. Bhd. and crossed "A/C PAYEE ONLY".',
            ],
            'ms-MY' => [
                'Sebut harga ini sah selama tiga puluh (30) hari dari tarikh dikeluarkan.',
                'Semua invois hendaklah dijelaskan dalam tempoh tiga puluh (30) hari dari tarikh invois. Invois akan dikemukakan secara bulanan melainkan dipersetujui sebaliknya.',
                'Semua harga yang dinyatakan adalah tidak termasuk SST dan sebarang cukai lain yang terpakai.',
                'Pengesahan perkhidmatan hendaklah disokong oleh Pesanan Belian rasmi atau Surat Setuju Terima yang dikeluarkan oleh Pelanggan.',
                'Harga tidak termasuk pemeriksaan perubatan, saringan kesihatan atau sebarang kos tambahan yang dikenakan oleh Pelanggan ke atas personel yang dibekalkan, melainkan telah dimaklumkan sebelum sebut harga ini dikeluarkan. Sebarang kos tersebut yang dibilkan kepada AMIOSH Resources Sdn. Bhd. akan dituntut sepenuhnya daripada Pelanggan.',
                'Harga tidak termasuk kos perjalanan dan penginapan bagi personel yang dibekalkan di luar lokasi tapak yang dinyatakan melainkan dinyatakan secara khusus. Jika perjalanan diperlukan, semua perbelanjaan berkaitan yang dibilkan kepada AMIOSH Resources Sdn. Bhd. akan dituntut daripada Pelanggan.',
                'Harga tidak termasuk kos latihan atau pensijilan yang diperlukan oleh Pelanggan (contohnya Authorised Entrant and Standby Person (AESP), Authorised Gas Tester (AGT), dan sebagainya). Kos ini akan dicaj secara berasingan dan dituntut daripada Pelanggan.',
                'Harga tidak termasuk liabiliti yang timbul daripada insiden yang disebabkan oleh tingkah laku personel yang dibekalkan berkaitan pasukan Pelanggan sehingga menyebabkan kerosakan kepada orang, harta benda, alam sekitar atau reputasi. AMIOSH Resources Sdn. Bhd. akan memberi kerjasama penuh dalam sebarang siasatan seterusnya.',
                'Pelanggan bertanggungjawab sepenuhnya terhadap sebarang kecederaan, kemudaratan atau kerosakan yang dialami oleh personel yang dibekalkan semasa menjalankan tugas di premis Pelanggan atau semasa perjalanan berkaitan kerja yang diatur oleh Pelanggan.',
                'Penamatan perkhidmatan hendaklah dimaklumkan secara bertulis dengan tempoh notis tidak kurang daripada satu (1) bulan dari tarikh akhir perkhidmatan yang dimaksudkan.',
                'Semua bayaran cek hendaklah dibuat atas nama AMIOSH Resources Sdn. Bhd. dan dipalang "A/C PAYEE ONLY".',
            ],
        ],
        'manpower_technical' => [
            'en' => [
                'Any variation or extension to the agreed scope of work must be supported by an official Variation Order or separate Purchase Order or Letter of Award and may be subject to revised pricing and deliverables.',
                'All project or site-related registrations required under Malaysian law or Client-specific regulations must be completed by the Client prior to project commencement. AMIOSH Resources Sdn. Bhd. will advise on OSH-related requirements. Where registration falls under AMIOSH Resources Sdn. Bhd.\'s responsibility, de-registration shall occur immediately after project completion or contract termination.',
                'The Client shall furnish all required information upon request--including past OSH reports, method statements, site layouts, personnel details, and competency records--to support accurate safety advisory and project execution.',
                'The Client must provide all necessary and task-specific Personal Protective Equipment (PPE) to the supplied personnel, including but not limited to full-body harnesses, self-contained breathing apparatus (SCBA), fire safety gear, and disposable PPE (e.g., gloves, earplugs, respirators). AMIOSH Resources Sdn. Bhd. will supply basic PPE such as safety shoes, helmets, and goggles.',
                'Normal working hours for supplied personnel shall be as scheduled by the Client, typically Monday to Friday or five (5) days per week. Any services rendered beyond this schedule shall be treated as overtime and charged at the applicable overtime rates.',
                'AMIOSH Resources Sdn. Bhd. reserves the right to adjust working hours of supplied personnel when necessary to safeguard their welfare.',
                'All personnel provided are entitled to leave as stipulated under the Employment Act 1955. Provisions under the Employment Act shall supersede any Client-imposed arrangements. AMIOSH Resources Sdn. Bhd. will not provide replacements during the personnel\'s entitled leave period.',
                'AMIOSH Resources Sdn. Bhd. reserves the right to replace any member of the Safety and Health team with personnel of equal qualification in the event of resignation, termination, or death. Such replacements will be made within one (1) month of notification. During this period, AMIOSH Resources Sdn. Bhd. shall not be subject to penalties or deductions of payment.',
            ],
            'ms-MY' => [
                'Sebarang perubahan atau lanjutan kepada skop kerja yang dipersetujui hendaklah disokong oleh Variation Order rasmi atau Pesanan Belian atau Surat Setuju Terima yang berasingan dan boleh tertakluk kepada semakan harga serta serahan kerja.',
                'Semua pendaftaran berkaitan projek atau tapak yang diperlukan di bawah undang-undang Malaysia atau peraturan khusus Pelanggan hendaklah diselesaikan oleh Pelanggan sebelum projek bermula. AMIOSH Resources Sdn. Bhd. akan memberi nasihat mengenai keperluan berkaitan OSH. Jika pendaftaran berada di bawah tanggungjawab AMIOSH Resources Sdn. Bhd., pembatalan pendaftaran hendaklah dibuat sebaik sahaja projek selesai atau kontrak ditamatkan.',
                'Pelanggan hendaklah menyediakan semua maklumat yang diperlukan apabila diminta, termasuk laporan OSH terdahulu, method statement, susun atur tapak, maklumat personel dan rekod kompetensi, bagi menyokong nasihat keselamatan dan pelaksanaan projek yang tepat.',
                'Pelanggan hendaklah menyediakan semua Peralatan Perlindungan Diri (PPE) yang diperlukan dan khusus kepada tugas untuk personel yang dibekalkan, termasuk tetapi tidak terhad kepada full-body harness, self-contained breathing apparatus (SCBA), peralatan keselamatan kebakaran dan PPE pakai buang (contohnya sarung tangan, earplug dan respirator). AMIOSH Resources Sdn. Bhd. akan membekalkan PPE asas seperti kasut keselamatan, topi keselamatan dan goggles.',
                'Waktu kerja biasa bagi personel yang dibekalkan adalah seperti jadual yang ditetapkan oleh Pelanggan, lazimnya Isnin hingga Jumaat atau lima (5) hari seminggu. Sebarang perkhidmatan di luar jadual ini akan dianggap sebagai kerja lebih masa dan dicaj mengikut kadar kerja lebih masa yang terpakai.',
                'AMIOSH Resources Sdn. Bhd. berhak melaraskan waktu kerja personel yang dibekalkan jika perlu bagi menjaga kebajikan mereka.',
                'Semua personel yang dibekalkan berhak mendapat cuti seperti yang diperuntukkan di bawah Akta Kerja 1955. Peruntukan di bawah Akta Kerja hendaklah mengatasi sebarang aturan yang dikenakan oleh Pelanggan. AMIOSH Resources Sdn. Bhd. tidak akan menyediakan pengganti semasa tempoh cuti yang menjadi hak personel tersebut.',
                'AMIOSH Resources Sdn. Bhd. berhak menggantikan mana-mana ahli pasukan Keselamatan dan Kesihatan dengan personel yang mempunyai kelayakan setara sekiranya berlaku peletakan jawatan, penamatan atau kematian. Penggantian tersebut akan dibuat dalam tempoh satu (1) bulan dari tarikh pemberitahuan. Dalam tempoh ini, AMIOSH Resources Sdn. Bhd. tidak tertakluk kepada penalti atau potongan bayaran.',
            ],
        ],
        'special_general' => [
            'en' => [
                'All prices stated exclude SST and any other applicable taxes unless explicitly stated.',
                'Payment shall be made within thirty (30) days from the invoice date unless otherwise agreed in writing by both parties.',
                'Prices do not cover additional costs incurred due to changes in scope, urgency, or special requirements unless discussed and agreed in writing.',
                'Any third-party costs, such as permits, facility usage, testing fees, or regulatory charges, are excluded unless specified in this quotation.',
                'This quotation is valid for thirty (30) days from the date of issuance, after which pricing and availability are subject to revision.',
                'Confirmation of services must be supported by an official Purchase Order (PO) or Letter of Award (LOA) issued by the Client.',
                'Any cancellation of the service must be notified in writing at least three (3) working days prior to the scheduled service date. All mobilisation and demobilisation costs incurred will be borne by the Client.',
                'All payments must be made to AMIOSH Resources Sdn. Bhd. and crossed "A/C PAYEE ONLY".',
            ],
            'ms-MY' => [
                'Semua harga yang dinyatakan adalah tidak termasuk SST dan sebarang cukai lain yang terpakai melainkan dinyatakan secara jelas.',
                'Bayaran hendaklah dibuat dalam tempoh tiga puluh (30) hari dari tarikh invois melainkan dipersetujui sebaliknya secara bertulis oleh kedua-dua pihak.',
                'Harga tidak meliputi kos tambahan yang ditanggung akibat perubahan skop, keperluan segera atau keperluan khas melainkan telah dibincangkan dan dipersetujui secara bertulis.',
                'Sebarang kos pihak ketiga seperti permit, penggunaan fasiliti, yuran ujian atau caj kawal selia adalah tidak termasuk melainkan dinyatakan dalam sebut harga ini.',
                'Sebut harga ini sah selama tiga puluh (30) hari dari tarikh dikeluarkan, selepas itu harga dan ketersediaan adalah tertakluk kepada semakan.',
                'Pengesahan perkhidmatan hendaklah disokong oleh Pesanan Belian (PO) rasmi atau Surat Setuju Terima (LOA) yang dikeluarkan oleh Pelanggan.',
                'Sebarang pembatalan perkhidmatan hendaklah dimaklumkan secara bertulis sekurang-kurangnya tiga (3) hari bekerja sebelum tarikh perkhidmatan yang dijadualkan. Semua kos mobilisasi dan demobilisasi yang telah ditanggung akan ditanggung oleh Pelanggan.',
                'Semua bayaran hendaklah dibuat kepada AMIOSH Resources Sdn. Bhd. dan dipalang "A/C PAYEE ONLY".',
            ],
        ],
        'special_technical' => [
            'en' => [
                'Any variation or extension to the scope of work must be confirmed via a formal Variation Order or new Purchase Order. Adjustments to cost and delivery may apply.',
                'The Client is responsible for providing accurate technical and site information necessary for project execution, including any special access requirements, regulations, or local compliance rules.',
                'Where the service includes equipment usage or site-based execution, the Client must ensure a safe, accessible, and compliant environment for the service provider team.',
                'If any specialised certifications, tools, or resources are required for the service, these must be provided or agreed upon prior to deployment.',
                'Normal working hours will follow the schedule defined by the Client unless otherwise stated. Work outside normal hours may be treated as overtime and invoiced accordingly.',
                'In the event of personnel-related services, AMIOSH Resources Sdn. Bhd. reserves the right to substitute any team member with one of equivalent or higher competency in the event of resignation, absence, or emergency.',
                'AMIOSH Resources Sdn. Bhd. will not be held liable for delays or interruptions caused by external factors beyond its control, such as weather conditions, regulatory delays, or force majeure events.',
            ],
            'ms-MY' => [
                'Sebarang perubahan atau lanjutan kepada skop kerja hendaklah disahkan melalui Variation Order rasmi atau Pesanan Belian baharu. Pelarasan kos dan penghantaran mungkin dikenakan.',
                'Pelanggan bertanggungjawab menyediakan maklumat teknikal dan tapak yang tepat serta diperlukan untuk pelaksanaan projek, termasuk sebarang keperluan akses khas, peraturan atau syarat pematuhan tempatan.',
                'Jika perkhidmatan melibatkan penggunaan peralatan atau pelaksanaan di tapak, Pelanggan hendaklah memastikan persekitaran yang selamat, boleh diakses dan mematuhi peraturan untuk pasukan penyedia perkhidmatan.',
                'Jika sebarang pensijilan, peralatan atau sumber khusus diperlukan untuk perkhidmatan, perkara tersebut hendaklah disediakan atau dipersetujui sebelum penempatan.',
                'Waktu kerja biasa akan mengikut jadual yang ditetapkan oleh Pelanggan melainkan dinyatakan sebaliknya. Kerja di luar waktu biasa boleh dianggap sebagai kerja lebih masa dan diinvois sewajarnya.',
                'Bagi perkhidmatan yang berkaitan personel, AMIOSH Resources Sdn. Bhd. berhak menggantikan mana-mana ahli pasukan dengan individu yang mempunyai kompetensi setara atau lebih tinggi sekiranya berlaku peletakan jawatan, ketidakhadiran atau kecemasan.',
                'AMIOSH Resources Sdn. Bhd. tidak akan bertanggungjawab terhadap kelewatan atau gangguan yang disebabkan oleh faktor luaran di luar kawalannya, seperti keadaan cuaca, kelewatan kawal selia atau kejadian force majeure.',
            ],
        ],
        'invoice' => [
            'en' => [
                'Payment is due within thirty (30) days from the date of this invoice.',
                'We reserve the right to pursue legal action for any invoices that remain unpaid beyond the due date.',
                'All services shall remain the property of AMIOSH RESOURCES SDN BHD until full payment has been received.',
                'Any disputes regarding this invoice must be submitted in writing within seven (7) days of receipt.',
                'All payments shall be made via wire transfer, direct bank deposit, or online transfer only.',
                'All cheque payments must be made payable to AMIOSH RESOURCES SDN BHD and crossed "A/C PAYEE ONLY".',
                'This invoice shall be governed by and construed in accordance with the laws of Malaysia.',
            ],
            'ms-MY' => [
                'Bayaran perlu dijelaskan dalam tempoh tiga puluh (30) hari dari tarikh invois ini.',
                'Kami berhak mengambil tindakan undang-undang bagi mana-mana invois yang masih belum dibayar selepas tarikh akhir bayaran.',
                'Semua perkhidmatan hendaklah kekal menjadi hak milik AMIOSH RESOURCES SDN BHD sehingga bayaran penuh diterima.',
                'Sebarang pertikaian berhubung invois ini hendaklah dikemukakan secara bertulis dalam tempoh tujuh (7) hari selepas penerimaan.',
                'Semua bayaran hendaklah dibuat melalui pindahan kawat, deposit bank terus atau pindahan dalam talian sahaja.',
                'Semua bayaran cek hendaklah dibuat atas nama AMIOSH RESOURCES SDN BHD dan dipalang "A/C PAYEE ONLY".',
                'Invois ini hendaklah ditadbir dan ditafsirkan mengikut undang-undang Malaysia.',
            ],
        ],
    ];

    public static function get(?string $language, string $key): array
    {
        $language = PdfLabels::normalize($language);

        return self::TERMS[$key][$language] ?? self::TERMS[$key]['en'] ?? [];
    }
}
